replicaCount: 1

frontend:
  image:
    repository: nginx
    tag: latest   # should be parameterized; 'latest' is discouraged
  service:
    type: LoadBalancer
    port: 80

backend:
  image:
    repository: hashicorp/http-echo
    tag: latest
  service:
    type: ClusterIP
    port: 8080

resources: {} # intentionally empty
