\
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: backend
        spec:
          containers:
            - name: backend
              image: hashicorp/http-echo:0.2.3
              args:
                - "-text=hello"
